/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"GPIO_Driver.h"

int main(void)
{
	GPIO_ClockControl(GPIOA, ENABLE);

	/*
	 * GPIOA
	 * GPIO_PIN_0
	 * GPIO_MODE_OUT
	 * GPIO_HIGH_SPEED
	 * GPIO_PU
	 * GPIO_PUSHPULL
	 * GPIO_AF1
	 */
	GPIO_Init(GPIOA, GPIO_PIN_0, GPIO_MODE_OUT,GPIO_HIGH_SPEED , GPIO_PU, GPIO_PUSHPULL, GPIO_AF1);
	GPIO_WriteToOut_Pin(GPIOA, GPIO_PIN_6,ENABLE);
    GPIO_DeInit(GPIOA);
    /* Loop forever */
	for(;;);
}
