/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<string.h>
#include<stm32f407xx_gpio_driver.h>
#include"stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay()
{
	for(uint32_t i=0;i<500000;i++);
}


/*
 * PB12-->SPI2-NSS
 * PB13-->SPI2-CLK
 * PB14-->SPI2-MISO
 * PB15-->SPI2-MOSI
 */

void SPI2_GPIOInits(void)
{
	GPIO_Handle_t SPI_Pins;
	SPI_Pins.pGPIOx = GPIOB;
	SPI_Pins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	SPI_Pins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_13;
	SPI_Pins.GPIO_PinConfig.GPIO_PinOpType = GPIO_PULL_UP;
	SPI_Pins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	SPI_Pins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_VHIG_SPEED;



	//SCLK
	GPIO_Init(&SPI_Pins);
    //NSS
//	SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_12;
//	GPIO_Init(GPIOB);
	//MISO
//	SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_14;
//	GPIO_Init(GPIOB);
    //MOSI
	SPI_Pins.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_15;
	GPIO_Init(GPIOB);


}

void SPI2_Init(void)
{
	SPI_Handle_t SPI2_Handle;
	SPI2_Handle.pSPIx = SPI2;
	SPI2_Handle.SPIConfig.SPI_DeviceMode = SPI_DEVICEMODE_Master;
	SPI2_Handle.SPIConfig.SPI_BusConfig = SPI_BUSCONFIG_FD;
	SPI2_Handle.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV2;
	SPI2_Handle.SPIConfig.SPI_DFF = SPI_DFF_8BIT;
	SPI2_Handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2_Handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI2_Handle.SPIConfig.SPI_SSM = SPI_SSM_EN;

	SPI_Init(&SPI2_Handle);
}

int main(void)

{

//	    GPIO_Handle_t GPIOLed,GPIOBtn;
//		GPIOLed.pGPIOx = GPIOD;
//		GPIOLed.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_12 ;
//		GPIOLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
//		GPIOLed.GPIO_PinConfig.GPIO_PinOpType = GPIO_OUTPUT_PUPD ;
//		GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD ;
//		GPIOLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_VHIG_SPEED ;
//
//		GPIO_ClockControl(GPIOD , ENABLE);
//		GPIO_Init(&GPIOLed);
//
//		GPIOBtn.pGPIOx = GPIOA;
//		GPIOBtn.GPIO_PinConfig.GPIO_PinNumber = GIPO_PIN_NO_0 ;
//		GPIOBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
//		GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD ;
//		GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_VHIG_SPEED ;
//		GPIO_ClockControl(GPIOA , ENABLE);
//	    GPIO_Init(&GPIOBtn);
//		while(1)
//		{
//			if(GPIO_ReadFromInputPin(GPIOA,GIPO_PIN_NO_0))
//			{
//				delay();
//				GPIO_TogglePin(GPIOD, GIPO_PIN_NO_12);
//			}
//
//
//		}
//
//



char user_data[] = "Hello Vinay";

//This Function is used to Initialize GPIO pins as SPI
SPI2_GPIOInits();

//This Function is used to initialize the SPI2 Pheripherals
SPI2_Init();


//ENable the SPI2 Pheripheral
SPI_SSIConfig(SPI2,ENABLE);
SPI_Pheripheral_Control(SPI2,ENABLE);

SPI_SendData(SPI2, (uint8_t*)user_data, strlen(user_data));

while(1);



}
